version: "3.8"

services:
  db:
    image: postgres:16.4
    container_name: postgres
    ports:
      - "5400:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: gobank
      POSTGRES_DB: postgres
    volumes:
      - database_data:/var/lib/postgresql/data:rw

volumes:
  database_data:
