# {{port}}
@port={{$dotenv LISTEN_ADDR}}
@api=http://localhost:{{port}}
# {{token}}
@token={{$dotenv JWT_TEST_TOKEN}}
# See: https://github.com/Huachao/vscode-restclient?tab=readme-ov-file#request-variables
# {{token}}
@token = {{loginAPI.response.body.token}}
# See: https://github.com/Huachao/vscode-restclient/issues/1029
# {{accountNumber}}
@accountNumber = {{listAccounts.response.body.$[0].number}}
@testAccountId=1

###
# @name listAccounts
# List available Accounts
GET {{api}}/account HTTP/1.1

###
# @name loginAPI
# Login
POST  {{api}}/login HTTP/1.1

{
    "number" : {{accountNumber}},
    "password" : "hunter88888"
}

###
# Login invalid password
POST  {{api}}/login HTTP/1.1

{
    "number" : {{accountNumber}},
    "password" : "hunter"
}

###
# Get an account
GET {{api}}/account/{{testAccountId}} HTTP/1.1
x-jwt-token: {{token}}

###
# Account number should be an int
GET {{api}}/account/"4" HTTP/1.1

###
# Create a new account
POST {{api}}/account HTTP/1.1
Content-Type: application/json

{
    "firstName": "zoltan",
    "lastName": "toma",
    "password": "secret"
}

###
# Delete an account
DELETE {{api}}/account/4 HTTP/1.1
x-jwt-token: {{token}}

###
# Method not allowed
OPTIONS  {{api}}/account HTTP/1.1

###
# Method not allowed
GET {{api}}/transfare HTTP/1.1

###
# Transfare
POST {{api}}/transfare HTTP/1.1
Content-Type: application/json

{
    "toAccount": 123456,
    "amount": 100000
}

